[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_market = "63aLZdtnc6ShpwYR2jEzEh78cjKUF1Tn2LK9DZhTnu4R"

[programs.devnet]
prediction_market = "63aLZdtnc6ShpwYR2jEzEh78cjKUF1Tn2LK9DZhTnu4R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./dev-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
